/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.uni.edu.programacion.views.panels;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
/**
 *
 * @author Pablo
 */
public class PnlMoney extends javax.swing.JPanel {

    /**
     * Creates new form PnlMoney
     */
    public PnlMoney() {
        initComponents();
    }

    public JLabel getCantidad() {
        return Cantidad;
    }

    public void setCantidad(JLabel Cantidad) {
        this.Cantidad = Cantidad;
    }

    public JLabel getResult() {
        return Result;
    }

    public void setResult(JLabel Result) {
        this.Result = Result;
    }

    public JButton getBtnDollar() {
        return btnDollar;
    }

    public void setBtnDollar(JButton btnDollar) {
        this.btnDollar = btnDollar;
    }

    public JButton getBtnCordoba() {
        return btnCordoba;
    }

    public void setBtnCordoba(JButton btnCordoba) {
        this.btnCordoba = btnCordoba;
    }

    public JButton getBtnNew() {
        return btnNew;
    }

    public void setBtnNew(JButton btnNew) {
        this.btnNew = btnNew;
    }

    public JTextField getjTextField1() {
        return TxtCantidad;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.TxtCantidad = jTextField1;
    }

    public JTextField getjTextField2() {
        return Txttotal;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.Txttotal = jTextField2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnDollar = new javax.swing.JButton();
        btnCordoba = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Cantidad = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        TxtCantidad = new javax.swing.JTextField();
        Txttotal = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        btnDollar.setText("Dolares");
        btnDollar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDollarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDollar);

        btnCordoba.setText("Córdobas");
        jPanel1.add(btnCordoba);

        btnNew.setText("Nuevo");
        jPanel1.add(btnNew);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        Cantidad.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(Cantidad, gridBagConstraints);

        Result.setText("Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(Result, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(TxtCantidad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(Txttotal, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDollarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDollarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDollarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Result;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField Txttotal;
    private javax.swing.JButton btnCordoba;
    private javax.swing.JButton btnDollar;
    private javax.swing.JButton btnNew;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
